name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - auth
    paths:
      - 'Backend/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: chatbotacr1752613890
  CONTAINER_NAME: chatbot-backend
  RESOURCE_GROUP: 1-52244e27-playground-sandbox
  CONTAINER_APP_NAME: chatbot-backend

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd Backend
          docker build -t ${{ env.CONTAINER_NAME }}:${{ github.sha }} .
          echo "✅ Docker image built successfully"

      - name: Display Deployment Info
        run: |
          echo "🚀 Build completed for commit: ${{ github.sha }}"
          echo "📦 Image: ${{ env.CONTAINER_NAME }}:${{ github.sha }}"
          echo "⚙️ Backend URL: https://chatbot-backend.calmhill-fb4ace7e.southcentralus.azurecontainerapps.io"
          echo "🔐 Authentication: API endpoints are protected with JWT tokens"
          echo ""
          echo "Note: Manual deployment to Azure Container Apps required due to authentication constraints" 