name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches:
      - auth
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_OCEAN_0B1783F10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Frontend"
          api_location: ""
          output_location: "out"
        env:
          NEXT_PUBLIC_API_URL: "https://chatbot-backend-1752416081.whitebeach-62d10d97.southcentralus.azurecontainerapps.io"

      - name: Display URLs
        run: |
          echo "🎉 Frontend Deployment Complete!"
          echo "🌐 Frontend URL: https://lemon-ocean-0b1783f10.1.azurestaticapps.net"
          echo "⚙️ Backend URL: https://chatbot-backend-1752416081.whitebeach-62d10d97.southcentralus.azurecontainerapps.io" 