name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - auth
    paths:
      - 'Backend/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: chatbotacr1752613890
  CONTAINER_NAME: chatbot-backend
  RESOURCE_GROUP: 1-52244e27-playground-sandbox
  CONTAINER_APP_NAME: chatbot-backend
  CONTAINER_APP_ENVIRONMENT: chatbot-env

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ./Backend
          registryUrl: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          imageToBuild: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          dockerfilePath: Dockerfile

      - name: Display URLs
        run: |
          echo "🎉 Backend Deployment Complete!"
          echo "⚙️ Backend URL: https://chatbot-backend.calmhill-fb4ace7e.southcentralus.azurecontainerapps.io"
          echo "🔐 Authentication: API endpoints are protected with JWT tokens" 